name: words_to_numbers
description: Dart implementation of words to numbers for converting english text to numbers
version: 1.0.0
homepage: https://github.com/buntagonalprism/words_to_numbers

environment:
  sdk: ^3.5.4

dev_dependencies:
  test: 

